# Generated by Django 2.2.5 on 2019-10-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=100)),
                ('game_type', models.CharField(max_length=30, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('diff_game', models.FloatField()),
                ('quality_index', models.FloatField()),
                ('team_count', models.IntegerField()),
                ('forum_resonance', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(to='backend.Team'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('game', models.ManyToManyField(to='backend.Game')),
                ('player', models.ManyToManyField(to='backend.Player')),
            ],
        ),
    ]
