# Generated by Django 2.2.5 on 2019-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190930_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
