# Generated by Django 2.2.5 on 2019-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forum_resonance',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
