# Generated by Django 2.2.5 on 2019-10-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Player'),
        ),
    ]
