# Generated by Django 2.2.5 on 2019-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.URLField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
