# Generated by Django 2.2.5 on 2019-11-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191021_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(blank=True, to='backend.Team'),
        ),
    ]
