# Generated by Django 2.2.5 on 2019-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191112_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='quality_index',
            field=models.FloatField(default=0.0),
        ),
    ]
