# Generated by Django 2.2.5 on 2019-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191001_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
