# Generated by Django 2.2.5 on 2019-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191115_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='quality_index',
            field=models.FloatField(),
        ),
    ]
