# Generated by Django 2.2.5 on 2019-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_team_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(to='backend.Team'),
        ),
    ]
