# Generated by Django 2.2.5 on 2020-01-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_congratulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='domen',
            field=models.CharField(default='vbratske', max_length=100),
        ),
    ]
