# Generated by Django 2.2.5 on 2019-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
