# Generated by Django 2.2.5 on 2019-10-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20191003_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Team')),
            ],
        ),
    ]
