# Generated by Django 2.2.5 on 2020-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_game_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Congratulation',
        ),
        migrations.AlterField(
            model_name='game',
            name='team_count',
            field=models.IntegerField(default=0),
        ),
    ]
