# Generated by Django 2.2.5 on 2020-12-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20201220_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'url')},
        ),
    ]
