# Generated by Django 2.2.5 on 2020-12-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201224_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='victory_count',
            field=models.IntegerField(default=0),
        ),
    ]
