# Generated by Django 2.2.5 on 2020-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_player_victory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_text',
            field=models.CharField(max_length=2000),
        ),
    ]
