# Generated by Django 2.2.5 on 2020-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201227_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_text',
            field=models.CharField(max_length=8000),
        ),
    ]
